# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MTQ5OTJjNjMyOTg3ODBmZmYzMDE4YWJkOGJmNzdjMjdiM2QxYzQ5OWJlYzI2ZDZiNjllNTMyMDBkNzAyZjgxMjEyY2Y0NTY0Yzc2ZDljYTRlZTg5NDljZWNlMjc1YTBjNmUxNzZhYmNhODM0ZWNmYmNiOTdiYmU0MTRiZDk2OWE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
